const defaultWatchLists = [
  {
    AssetIds: [
      'AUDCHF',
      'AUDGBP',
      'AUDJPY',
      'AUDUSD',
      'BTCAUD',
      'BTCCHF',
      'BTCGBP',
      'BTCJPY',
      'BTCLKK',
      'BTCLKK1Y',
      'BTCUSD',
      'ETCUSD',
      'ETHBTC',
      'ETHCHF',
      'ETHLKK',
      'ETHUSD',
      'GBPCHF',
      'GBPJPY',
      'GBPUSD',
      'LKK1YAUD',
      'LKK1YCHF',
      'LKK1YGBP',
      'LKK1YJPY',
      'LKK1YLKK',
      'LKK1YUSD',
      'LKKAUD',
      'LKKCHF',
      'LKKGBP',
      'LKKJPY',
      'LKKUSD',
      'QNTCHF',
      'QNTGBP',
      'QNTJPY',
      'QNTUSD',
      'SLRBTC',
      'SLRCHF',
      'SLRGBP',
      'SLRJPY',
      'SLRUSD',
      'TIMEBTC',
      'TIMECHF',
      'TIMEGBP',
      'TIMEJPY',
      'TIMELKK',
      'TIMEUSD',
      'USDCHF',
      'USDJPY'
    ],
    Id: '284816c3-037d-4678-aaac-61311d6fe03a',
    Name: 'All assets',
    Order: 0,
    ReadOnly: true
  }
];

export default defaultWatchLists;
